services:
  - type: web
    name: hirebot-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DB
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true

  - type: web
    name: hirebot-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_BASE_URL
        value: https://hirebot-backend.onrender.com/api/v1
